const e = {
  common: {
    version: "版本",
    health: "健康状况",
    ok: "正常",
    offline: "离线",
    connect: "连接",
    refresh: "刷新",
    enabled: "已启用",
    disabled: "已禁用",
    na: "不适用",
    docs: "文档",
    resources: "资源",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    add: "添加",
    remove: "移除",
    close: "关闭",
    confirm: "确认",
    loading: "加载中",
    error: "错误",
    success: "成功",
    warning: "警告",
    info: "信息",
    copy: "复制",
    copied: "已复制",
    search: "搜索",
    filter: "筛选",
    clear: "清除",
    reset: "重置",
    apply: "应用",
    update: "更新",
    start: "启动",
    stop: "停止",
    restart: "重启",
    pause: "暂停",
    resume: "恢复",
    retry: "重试",
    back: "返回",
    next: "下一步",
    previous: "上一步",
    finish: "完成",
    skip: "跳过",
    yes: "是",
    no: "否",
    all: "全部",
    none: "无",
    select: "选择",
    selected: "已选择",
    default: "默认",
    custom: "自定义",
    more: "更多",
    less: "更少",
    show: "显示",
    hide: "隐藏",
    expand: "展开",
    collapse: "折叠",
    details: "详情",
    settings: "设置",
    preferences: "偏好设置",
    options: "选项",
    actions: "操作",
    status: "状态",
    name: "名称",
    description: "描述",
    type: "类型",
    value: "值",
    key: "键",
    id: "ID",
    date: "日期",
    time: "时间",
    duration: "持续时间",
    size: "大小",
    count: "数量",
    total: "总计",
    used: "已使用",
    available: "可用",
    active: "活跃",
    inactive: "非活跃",
    online: "在线",
    connected: "已连接",
    disconnected: "已断开",
    pending: "等待中",
    completed: "已完成",
    failed: "失败",
    unknown: "未知",
    empty: "空",
    required: "必填",
    optional: "可选",
    example: "示例",
    hint: "提示",
    note: "注意",
    tip: "技巧"
  },
  nav: {
    chat: "聊天",
    control: "控制",
    agent: "代理",
    settings: "设置",
    expand: "展开侧边栏",
    collapse: "折叠侧边栏",
    home: "首页",
    dashboard: "仪表板",
    help: "帮助",
    about: "关于",
    logout: "登出"
  },
  tabs: {
    agents: "代理",
    overview: "概览",
    channels: "频道",
    instances: "实例",
    sessions: "会话",
    usage: "使用情况",
    cron: "定时任务",
    skills: "技能",
    nodes: "节点",
    chat: "聊天",
    config: "配置",
    debug: "调试",
    logs: "日志",
    tools: "工具",
    identity: "身份",
    workspace: "工作区",
    history: "历史",
    analytics: "分析",
    monitoring: "监控"
  },
  subtitles: {
    agents: "管理代理工作区、工具和身份。",
    overview: "网关状态、入口点和快速健康读取。",
    channels: "管理频道和设置。",
    instances: "来自已连接客户端和节点的在线信号。",
    sessions: "检查活动会话并调整每个会话的默认设置。",
    usage: "监控 API 使用情况和成本。",
    cron: "安排唤醒和重复的代理运行。",
    skills: "管理技能可用性和 API 密钥注入。",
    nodes: "配对设备、功能和命令公开。",
    chat: "用于快速干预的直接网关聊天会话。",
    config: "安全地编辑 ~/.openclaw/openclaw.json。",
    debug: "网关快照、事件和手动 RPC 调用。",
    logs: "网关文件日志的实时追踪。",
    tools: "管理可用工具和集成。",
    identity: "管理身份和认证设置。"
  },
  overview: {
    access: {
      title: "网关访问",
      subtitle: "仪表板连接的位置及其身份验证方式。",
      wsUrl: "WebSocket URL",
      token: "网关令牌",
      password: "密码 (不存储)",
      sessionKey: "默认会话密钥",
      language: "语言",
      connectHint: "点击连接以应用连接更改。",
      trustedProxy: "通过受信任代理认证。"
    },
    snapshot: {
      title: "快照",
      subtitle: "最新的网关握手信息。",
      status: "状态",
      uptime: "运行时间",
      tickInterval: "刻度间隔",
      lastChannelsRefresh: "最后频道刷新",
      channelsHint: "使用频道链接 WhatsApp、Telegram、Discord、Signal 或 iMessage。"
    },
    stats: {
      instances: "实例",
      instancesHint: "过去 5 分钟内的在线信号。",
      sessions: "会话",
      sessionsHint: "网关跟踪的最近会话密钥。",
      cron: "定时任务",
      cronNext: "下次唤醒 {time}"
    },
    notes: {
      title: "备注",
      subtitle: "远程控制设置的快速提醒。",
      tailscaleTitle: "Tailscale serve",
      tailscaleText: "首选 serve 模式以通过 tailnet 身份验证将网关保持在回环地址。",
      sessionTitle: "会话清理",
      sessionText: "使用 /new 或 sessions.patch 重置上下文。",
      cronTitle: "定时任务提醒",
      cronText: "为重复运行使用隔离的会话。"
    },
    auth: {
      required: "此网关需要身份验证。添加令牌或密码，然后点击连接。",
      failed: "身份验证失败。请使用 {command} 重新复制令牌化 URL，或更新令牌，然后点击连接。"
    },
    pairing: {
      hint: "此设备需要网关主机的配对批准。",
      mobileHint: "在手机上？从桌面运行 openclaw dashboard --no-open 复制完整 URL（包括 #token=...）。"
    },
    insecure: {
      hint: "此页面为 HTTP，因此浏览器阻止设备标识。请使用 HTTPS (Tailscale Serve) 或在网关主机上打开 {url}。",
      stayHttp: "如果您必须保持 HTTP，请设置 {config} (仅限令牌)。"
    }
  },
  chat: {
    disconnected: "已断开与网关的连接。",
    refreshTitle: "刷新聊天数据",
    thinkingToggle: "切换助手思考/工作输出",
    focusToggle: "切换专注模式 (隐藏侧边栏 + 页面页眉)",
    onboardingDisabled: "引导期间禁用",
    sendMessage: "发送消息",
    typeMessage: "输入消息...",
    clearChat: "清除聊天",
    newChat: "新聊天",
    loadMore: "加载更多",
    noMessages: "暂无消息",
    messageDeleted: "消息已删除",
    messageSent: "消息已发送",
    messageError: "发送失败",
    thinking: "思考中...",
    working: "工作中...",
    responding: "回复中...",
    waiting: "等待中...",
    retry: "重试",
    copy: "复制",
    delete: "删除",
    edit: "编辑",
    regenerate: "重新生成"
  },
  channels: {
    title: "频道管理",
    subtitle: "配置和管理消息频道。",
    whatsapp: {
      title: "WhatsApp",
      description: "通过 WhatsApp Web 连接。",
      login: "登录",
      logout: "登出",
      scan: "扫描二维码",
      waiting: "等待扫描...",
      connected: "已连接",
      disconnected: "已断开",
      connecting: "连接中...",
      forceLogin: "强制重新登录"
    },
    telegram: {
      title: "Telegram",
      description: "通过 Telegram Bot 连接。",
      botToken: "Bot Token",
      webhookUrl: "Webhook URL"
    },
    discord: {
      title: "Discord",
      description: "通过 Discord Bot 连接。",
      botToken: "Bot Token",
      guildId: "Guild ID"
    },
    signal: {
      title: "Signal",
      description: "通过 Signal 连接。"
    },
    imessage: {
      title: "iMessage",
      description: "通过 iMessage 连接 (仅限 macOS)。"
    },
    nostr: {
      title: "Nostr",
      description: "通过 Nostr 协议连接。"
    },
    status: {
      online: "在线",
      offline: "离线",
      connecting: "连接中",
      error: "错误",
      unknown: "未知"
    },
    actions: {
      refresh: "刷新状态",
      configure: "配置",
      enable: "启用",
      disable: "禁用",
      test: "测试连接"
    }
  },
  sessions: {
    title: "会话管理",
    subtitle: "管理活动会话和上下文。",
    sessionKey: "会话密钥",
    created: "创建时间",
    lastActivity: "最后活动",
    messageCount: "消息数量",
    context: "上下文",
    clearContext: "清除上下文",
    deleteSession: "删除会话",
    exportSession: "导出会话",
    importSession: "导入会话",
    noSessions: "暂无活动会话",
    active: "活跃",
    idle: "空闲",
    expired: "已过期"
  },
  skills: {
    title: "技能管理",
    subtitle: "配置代理技能和 API 密钥。",
    skillName: "技能名称",
    enabled: "已启用",
    disabled: "已禁用",
    apiKey: "API 密钥",
    configure: "配置",
    test: "测试",
    noSkills: "暂无可用技能"
  },
  nodes: {
    title: "节点管理",
    subtitle: "管理配对设备和功能。",
    nodeId: "节点 ID",
    nodeName: "节点名称",
    capabilities: "功能",
    lastSeen: "最后活动",
    pair: "配对",
    unpair: "取消配对",
    approve: "批准",
    reject: "拒绝",
    pending: "待批准",
    paired: "已配对",
    noPendingNodes: "暂无待配对节点",
    noPairedNodes: "暂无已配对节点"
  },
  cron: {
    title: "定时任务",
    subtitle: "管理计划任务和定时执行。",
    jobName: "任务名称",
    schedule: "计划",
    nextRun: "下次执行",
    lastRun: "上次执行",
    status: "状态",
    enabled: "已启用",
    disabled: "已禁用",
    running: "运行中",
    idle: "空闲",
    failed: "失败",
    create: "创建任务",
    edit: "编辑",
    delete: "删除",
    run: "立即执行",
    pause: "暂停",
    resume: "恢复",
    noJobs: "暂无定时任务"
  },
  config: {
    title: "配置",
    subtitle: "编辑 OpenClaw 配置文件。",
    mode: {
      form: "表单模式",
      raw: "原始模式"
    },
    save: "保存",
    apply: "应用",
    reset: "重置",
    reload: "重新加载",
    valid: "配置有效",
    invalid: "配置无效",
    unsavedChanges: "有未保存的更改",
    saveFirst: "请先保存更改",
    confirmReset: "确定要重置所有更改吗？",
    configPath: "配置文件路径",
    lastModified: "最后修改",
    issues: "问题",
    noIssues: "无问题",
    validation: {
      required: "此字段为必填",
      invalid: "无效的值",
      type: "类型错误"
    }
  },
  debug: {
    title: "调试",
    subtitle: "网关调试和诊断工具。",
    snapshot: {
      title: "快照",
      subtitle: "查看网关当前状态快照。",
      refresh: "刷新快照",
      download: "下载快照"
    },
    events: {
      title: "事件",
      subtitle: "实时事件流。",
      subscribe: "订阅",
      unsubscribe: "取消订阅",
      clear: "清除",
      noEvents: "暂无事件"
    },
    rpc: {
      title: "RPC 调用",
      subtitle: "手动执行 RPC 方法。",
      method: "方法",
      params: "参数",
      execute: "执行",
      result: "结果",
      error: "错误",
      history: "历史记录"
    }
  },
  logs: {
    title: "日志",
    subtitle: "查看网关日志。",
    level: {
      all: "全部",
      debug: "调试",
      info: "信息",
      warn: "警告",
      error: "错误"
    },
    filter: "筛选",
    search: "搜索",
    clear: "清除",
    download: "下载",
    autoScroll: "自动滚动",
    timestamp: "时间戳",
    source: "来源",
    message: "消息",
    noLogs: "暂无日志"
  },
  agents: {
    title: "代理管理",
    subtitle: "管理代理工作区和身份。",
    workspace: {
      title: "工作区",
      subtitle: "管理代理工作区。",
      name: "名称",
      path: "路径",
      create: "创建",
      delete: "删除",
      select: "选择",
      noWorkspaces: "暂无工作区"
    },
    tools: {
      title: "工具",
      subtitle: "管理可用工具。",
      name: "名称",
      description: "描述",
      enabled: "已启用",
      disabled: "已禁用",
      configure: "配置",
      noTools: "暂无可用工具"
    },
    identity: {
      title: "身份",
      subtitle: "管理代理身份。",
      name: "名称",
      displayName: "显示名称",
      avatar: "头像",
      bio: "简介",
      create: "创建",
      edit: "编辑",
      delete: "删除",
      noIdentities: "暂无身份"
    }
  },
  usage: {
    title: "使用情况",
    subtitle: "监控 API 使用情况和成本。",
    period: {
      today: "今天",
      week: "本周",
      month: "本月",
      custom: "自定义"
    },
    metrics: {
      totalCalls: "总调用次数",
      totalTokens: "总 Token 数",
      totalCost: "总成本",
      avgLatency: "平均延迟"
    },
    breakdown: {
      byModel: "按模型",
      byEndpoint: "按端点",
      byTime: "按时间"
    },
    noData: "暂无使用数据"
  },
  tools: {
    bash: "Bash 命令",
    read: "读取文件",
    write: "写入文件",
    edit: "编辑文件",
    browser: "浏览器",
    search: "搜索",
    mcp: "MCP 工具",
    computer: "计算机控制",
    glob: "文件匹配",
    grep: "文本搜索",
    ls: "列出目录",
    notebook: "Notebook"
  },
  errors: {
    connectionFailed: "连接失败",
    authFailed: "身份验证失败",
    timeout: "请求超时",
    serverError: "服务器错误",
    networkError: "网络错误",
    unknown: "未知错误",
    invalidInput: "输入无效",
    permissionDenied: "权限被拒绝",
    notFound: "未找到",
    alreadyExists: "已存在",
    rateLimited: "请求过于频繁",
    configError: "配置错误",
    parseError: "解析错误"
  },
  status: {
    online: "在线",
    offline: "离线",
    connecting: "连接中",
    connected: "已连接",
    disconnected: "已断开",
    reconnecting: "重新连接中",
    error: "错误",
    loading: "加载中",
    ready: "就绪",
    busy: "繁忙",
    idle: "空闲",
    paused: "已暂停",
    running: "运行中",
    stopped: "已停止",
    pending: "等待中",
    completed: "已完成",
    failed: "失败",
    cancelled: "已取消"
  },
  actions: {
    save: "保存",
    saveAll: "全部保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    add: "添加",
    remove: "移除",
    create: "创建",
    update: "更新",
    refresh: "刷新",
    reload: "重新加载",
    reset: "重置",
    clear: "清除",
    copy: "复制",
    paste: "粘贴",
    cut: "剪切",
    undo: "撤销",
    redo: "重做",
    selectAll: "全选",
    deselectAll: "取消全选",
    confirm: "确认",
    apply: "应用",
    close: "关闭",
    open: "打开",
    download: "下载",
    upload: "上传",
    export: "导出",
    import: "导入",
    enable: "启用",
    disable: "禁用",
    start: "启动",
    stop: "停止",
    restart: "重启",
    pause: "暂停",
    resume: "恢复",
    retry: "重试",
    test: "测试",
    run: "运行",
    execute: "执行",
    submit: "提交",
    send: "发送",
    connect: "连接",
    disconnect: "断开",
    login: "登录",
    logout: "登出",
    register: "注册",
    subscribe: "订阅",
    unsubscribe: "取消订阅",
    follow: "关注",
    unfollow: "取消关注",
    like: "喜欢",
    unlike: "取消喜欢",
    share: "分享",
    pin: "固定",
    unpin: "取消固定",
    archive: "归档",
    unarchive: "取消归档",
    mute: "静音",
    unmute: "取消静音",
    block: "屏蔽",
    unblock: "取消屏蔽",
    report: "举报",
    flag: "标记",
    approve: "批准",
    reject: "拒绝",
    accept: "接受",
    decline: "拒绝",
    invite: "邀请",
    join: "加入",
    leave: "离开",
    merge: "合并",
    split: "拆分",
    move: "移动",
    rename: "重命名",
    duplicate: "复制",
    clone: "克隆"
  },
  languages: {
    en: "English",
    zhCN: "简体中文 (简体中文)",
    zhTW: "繁體中文 (繁体中文)",
    ptBR: "Português (巴西葡萄牙语)"
  },
  profile: {
    title: "编辑资料",
    account: "账户",
    username: "用户名",
    displayName: "显示名称",
    bio: "简介",
    avatarUrl: "头像 URL",
    bannerUrl: "横幅 URL",
    website: "网站",
    nip05: "NIP-05 验证",
    lud16: "闪电地址",
    save: "保存更改",
    cancel: "取消",
    saving: "保存中...",
    saved: "已保存",
    error: "保存失败",
    hints: {
      username: "短用户名 (例如: satoshi)",
      displayName: "您的完整显示名称",
      bio: "简短的个人简介或描述",
      avatarUrl: "HTTPS 格式的头像图片链接",
      bannerUrl: "HTTPS 格式的横幅图片链接",
      website: "您的个人网站",
      nip05: "NIP-05 验证标识符",
      lud16: "闪电网络收款地址"
    }
  },
  instances: {
    title: "实例",
    subtitle: "来自已连接客户端和节点的在线信号。",
    nodeId: "节点 ID",
    deviceId: "设备 ID",
    platform: "平台",
    version: "版本",
    lastPing: "最后心跳",
    uptime: "运行时间",
    noInstances: "暂无活跃实例",
    refresh: "刷新",
    details: "详情"
  },
  time: {
    now: "刚刚",
    secondsAgo: "{count} 秒前",
    minutesAgo: "{count} 分钟前",
    hoursAgo: "{count} 小时前",
    daysAgo: "{count} 天前",
    weeksAgo: "{count} 周前",
    monthsAgo: "{count} 月前",
    yearsAgo: "{count} 年前",
    inSeconds: "{count} 秒后",
    inMinutes: "{count} 分钟后",
    inHours: "{count} 小时后",
    inDays: "{count} 天后",
    inWeeks: "{count} 周后",
    inMonths: "{count} 月后",
    inYears: "{count} 年后"
  },
  validation: {
    required: "此字段为必填",
    minLength: "最少需要 {min} 个字符",
    maxLength: "最多允许 {max} 个字符",
    min: "最小值为 {min}",
    max: "最大值为 {max}",
    email: "请输入有效的邮箱地址",
    url: "请输入有效的 URL",
    pattern: "格式不正确",
    integer: "请输入整数",
    number: "请输入数字",
    positive: "请输入正数",
    negative: "请输入负数",
    unique: "该值已存在",
    confirm: "两次输入不一致"
  },
  placeholders: {
    search: "搜索...",
    enterValue: "请输入值",
    selectOption: "请选择",
    enterUrl: "https://example.com",
    enterEmail: "example@domain.com",
    enterPassword: "请输入密码",
    enterUsername: "请输入用户名",
    enterMessage: "输入消息...",
    enterCode: "请输入代码",
    enterName: "请输入名称",
    enterDescription: "请输入描述"
  },
  confirmations: {
    delete: "确定要删除吗？此操作无法撤销。",
    reset: "确定要重置吗？所有未保存的更改将丢失。",
    discard: "确定要放弃更改吗？",
    logout: "确定要登出吗？",
    clear: "确定要清除所有内容吗？",
    disconnect: "确定要断开连接吗？"
  },
  empty: {
    noData: "暂无数据",
    noResults: "未找到结果",
    noItems: "暂无项目",
    noMessages: "暂无消息",
    noNotifications: "暂无通知",
    noActivity: "暂无活动"
  }
};

export { e as zh_CN };

